apiVersion: v1
kind: Service
metadata:
  name: custom-service
  labels:
    app: custom-app
spec:
  type: ClusterIP
  selector:
    app: custom-app
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: 8080